---
name: jmeter-runner-action
description: Github action for running a load test using Jmeter. Included with plugins:- concurrency thread, throughput shaping timer
author: QA-Performance-Engineering <QA-Performance-Engineering@betssongroup.com>

inputs:
  testFilePath:
    description: The path to the JMX test file
    required: true
  outputReportsFolder:
    description: The folder where the JMeter reports will be published
    required: false
    default: reports/
  args:
    required: false
    description: |
      Optional arguments that are passed to the JMeter tool

      Options:
        -p, --propfile <argument>
        -q, --addprop <argument>
        -i, --jmeterlogconf <argument>
        -j, --jmeterlogfile <argument>
        -s, --server
        -E, --proxyScheme <argument>
        -H, --proxyHost <argument>
        -P, --proxyPort <argument>
        -N, --nonProxyHosts<argument>
        -u, --username <argument>
        -a, --password <argument>
        -J, --jmeterproperty <argument>=<value>
        -G, --globalproperty <argument>=<value>
        -D, --systemproperty <argument>=<value>
        -S, --systemPropertyFile <argument>
        -f, --forceDeleteResultFile
        -L, --loglevel <argument>=<value>
        -r, --runremote
        -R, --remotestart <argument>
        -d, --homedir <argument>
        -X, --remoteexit
        -g, --reportonly <argument>

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-n"
    - "-t"
    - "${{ inputs.testFilePath }}"
    - "-l"
    - "jmeter_log.log"
    - "-e"
    - "-f"
    - "-o"
    - "${{ inputs.outputReportsFolder }}"
    - "${{ inputs.args }}"

branding:
  color: blue
  icon: zap
